spring:
  application:
    name: sellerx
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5434/sellerx_db?createDatabaseIfNotExist=true
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 3600 # 1h - test
    refreshTokenExpiration: 604800 # 7d

# Turkey timezone configuration
timezone: Europe/Istanbul

# Webhook configuration
app:
  webhook:
    enabled: false # Default: disabled for development
    base-url: ${WEBHOOK_BASE_URL:http://localhost:8080}
    api-key: ${WEBHOOK_API_KEY:sellerx-webhook-key}

logging:
  level:
    com.ecommerce.sellerx.products: INFO
    com.ecommerce.sellerx.orders: INFO
    org.hibernate.SQL: INFO
    root: INFO
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: pass123
#    key-store-type: PKCS12
#    key-alias: springboot
