spring:
  application:
    name: sellerx
  datasource:
    # Alternative: Use separate environment variables if DATABASE_URL doesn't work
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sellerx}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    # Don't set URL here, let it use the datasource URL automatically
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 3600 # 1h
    refreshTokenExpiration: 604800 # 7d

# Production cookie settings
app:
  cookie:
    secure: true
    httpOnly: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.ecommerce.sellerx: INFO
