spring:
  application:
    name: sellerx
  datasource:
    url: jdbc:postgresql://localhost:5434/sellerx_db?createDatabaseIfNotExist=true
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d